services:
  - type: web
    name: slime-trackerx-pro
    runtime: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        value: mongodb+srv://mrdev:dev091339@cluster0.grjlq7v.mongodb.net/prosuite
      - key: OWNER_ID
        value: 7271063368
      - key: CHANNEL
        value: "@devxtechzone"
      - key: PORT
        value: 3000
    plan: free
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
